"""Independent v46 source-alignment and spawn oracle.

Expected cells are copied from the approved mask audit, not generated by the
runtime grid or collision functions under test.
"""
import math, pathlib, sys
sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
from _harness import game, Tally

AUDIT_OPEN = [(28, 8), (26, 11), (27, 8)]
AUDIT_WATER = [(24, 11), (25, 11), (26, 11)]
with game(width=844, height=390) as (pg, errs):
    t = Tally()
    chars = pg.evaluate("([a,b])=>[Arena.grid[a[1]][a[0]],Arena.grid[b[1]][b[0]]].map(String)", [AUDIT_OPEN[0], AUDIT_WATER[0]])
    t.check("former false-solid route is open floor", chars[0] == '.')
    t.check("audited lake shoreline remains water", chars[1] == '~')
    t.check("spawn marker is on the audited open route", pg.evaluate("Arena.grid[8][27] === 'S'"))
    t.check("all audited open cells are walkable", all(not pg.evaluate("([c,r])=>Arena.isSolid(c,r)", p) for p in AUDIT_OPEN))
    spawn = pg.evaluate("Arena.spawn()")
    h = pg.evaluate("Player.h")
    t.check("runtime spawn body is clear", not pg.evaluate("([x,y,h])=>Arena.isSolidAt(x,y,h)", [spawn['x'], spawn['y'], h]))
    t.check("prop inventory includes the formerly missing spawn stump", pg.evaluate("Arena.props.some(p=>p.id==='stump-20'&&Math.abs(p.x-1139.5*Arena.T/43)<.1)"))
    t.check("prop-aware route selection stays on free cells", pg.evaluate("!!Arena.path(27,8,28,8)"))
    t.finish("source alignment", errs)
